In [2]:
import numpy as np 

Creations

In [3]:
arr=np.array([3,6,8,4,9])
arr 

array([3, 6, 8, 4, 9])

In [5]:
arr2=np.arange(2,7)
arr2 

array([2, 3, 4, 5, 6])

In [11]:
arr3=np.linspace(1,5,5)
arr3

array([1., 2., 3., 4., 5.])

In [20]:
arr4=np.ones((2,2,2),dtype=int)
arr4

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [17]:
arr4.dtype

dtype('float64')

In [18]:
arr4.size

8

In [19]:
arr4.shape

(2, 2, 2)

In [21]:
arr5=np.zeros(8)
arr5 


array([0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
arr6=np.zeros_like([4,5,7])
arr6 

array([0, 0, 0])

In [23]:
arr7=np.eye(5)
arr7 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
arr8=np.empty(7)
arr8 

array([0., 0., 0., 0., 0., 0., 0.])

In [44]:
arr9=np.random.rand(2,3)
arr9 

array([[0.41032315, 0.64566604, 0.12805331],
       [0.03103554, 0.49208844, 0.48051727]])

In [47]:
arr10=np.arange(1,10).reshape((3,3))
arr10

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr11=np.arange(10)
a=arr11[2:7,np.newaxis]
a 


array([[2],
       [3],
       [4],
       [5],
       [6]])

In [60]:
sm1=np.array([2,5,6])
sm2=np.array([6,7,8])
np.concatenate([sm1,sm2])

array([2, 5, 6, 6, 7, 8])

In [85]:
dummy=np.array([6,7,89,34,23,67])

# calculations 
# dummy+1
# dummy*2

# aggragation 

# np.sum(dummy)
# np.min(dummy)
# np.max(dummy)
# np.mean(dummy)
# np.median(dummy)
# np.std(dummy)

# dummy=np.array([6,7,89,34,23,67])
# perfoming conditional 


# dummy[np.array([6,7,89,34,23,67])<30]

dummy.sort()

dummy



array([ 6,  7, 23, 34, 67, 89])